Fix compiler warnings: 'discarded-qualifiers'.
Changes fix following warnings:
- forwarder/forwarder.c:311:37: error: passing argument 2 of ‘ndn_interest_tlv_encode’ discards ‘const’ qualifier from pointer target type

NOTE: the cause of this warning is 'ndn_interest_tlv_encode' in
which name components are updated to cater for a SHA256 digest.