Fix compiler warnings: 'unused-but-set-variable'
Changes fix following warnings:
- forwarder/name-tree.c:83:17: error: variable ‘last_node’ set but not used

NOTE: this unused variable seems to be remainder of a 'copy/paste'
action!