Fix compiler warning: 'discarded-qualifiers'.
Changes fix following errors:
- ndn-lite/app-support/security-bootstrapping.c:286:46: error: passing argument 5 of ‘ndn_forwarder_express_interest’ discards ‘const’ qualifier from pointer target type

NOTE: This specific error was caused by inconsistend programming in
declaring a pointer as const in one place but assigning it to other
pointers which are not const.